### PR TITLE
Allow disabling of limits

### PR DESCRIPTION
**Pull request by ekzyis**
I am running this software with a regtest node for local dev. I sometimes run into these limits.

With this patch, one can disable the limits provided by `--max-amount` and `--daily-limit` by passing in 0.

### CODE REVIEW

**Comment by benthecarman** [comment]
Can you add the same for `PayKeysend` ?

**Comment by ekzyis** [comment]
Done!

**Comment by benthecarman** [comment]
Looks like you need to run cargo fmt

**Comment by ekzyis** [comment]
Oh, didn't see. Done!

**Review by benthecarman — APPROVED** [review]

**Pull request merged**
